include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
