name: big_root_market
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1

  google_sign_in: ^6.3.0

  image_picker: ^1.1.2
  intl: ^0.20.2
  dots_indicator: ^4.0.1

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  flutter_image_compress: ^2.4.0

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  #firebase_storage: 유료화 되면서 supabase_flutter로 대체하여 사용할 예정.
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/